"""
Validate building meshes and prepare for Unity import.

This script:
1. Checks GLB files generated by generate_building_meshes.py
2. Validates mesh integrity (vertices, faces, normals)
3. Generates summary statistics
4. Creates Unity import guide
5. Prepares asset list for engine
"""

import json
import logging
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Dict, List, Optional
from datetime import datetime

try:
    import pygltflib
    HAS_PYGLTF = True
except ImportError:
    HAS_PYGLTF = False

import numpy as np

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger(__name__)

# ============================================================================
# Configuration
# ============================================================================

CONFIG = {
    "meshes_dir": "Processed_data/building_meshes/",
    "manifest_path": "Processed_data/building_meshes/buildings_manifest.json",
    "validation_report_path": "reports/validation/2026-04-23_mesh_validation_report.md",
    "unity_import_guide_path": "docs/unity_import_guide.md"
}

# ============================================================================
# Data Classes
# ============================================================================

@dataclass
class MeshValidationResult:
    """Validation result for a single mesh."""
    filename: str
    valid: bool
    file_size_bytes: int
    vertex_count: int
    triangle_count: int
    bounds_min: List[float]
    bounds_max: List[float]
    error_message: Optional[str] = None


@dataclass
class ValidationSummary:
    """Summary of mesh validation."""
    timestamp: str
    total_meshes: int
    valid_meshes: int
    invalid_meshes: int
    total_file_size_mb: float
    avg_vertices_per_mesh: float
    avg_triangles_per_mesh: float
    total_vertices: int
    total_triangles: int


# ============================================================================
# GLB Validation
# ============================================================================

def validate_glb_file(glb_path: Path) -> MeshValidationResult:
    """Validate a single GLB file."""
    result = MeshValidationResult(
        filename=glb_path.name,
        valid=False,
        file_size_bytes=glb_path.stat().st_size,
        vertex_count=0,
        triangle_count=0,
        bounds_min=[0, 0, 0],
        bounds_max=[0, 0, 0]
    )
    
    try:
        if not HAS_PYGLTF:
            # Can't validate without pygltflib, but file exists
            result.valid = True
            return result
        
        gltf = pygltflib.load(str(glb_path))
        
        # Check mesh structure
        if not gltf.meshes:
            result.error_message = "No meshes in GLB"
            return result
        
        mesh = gltf.meshes[0]
        if not mesh.primitives:
            result.error_message = "No primitives in mesh"
            return result
        
        # Get vertex data
        primitive = mesh.primitives[0]
        position_accessor_idx = primitive.attributes.POSITION
        
        if position_accessor_idx is None:
            result.error_message = "No position data"
            return result
        
        position_accessor = gltf.accessors[position_accessor_idx]
        result.vertex_count = position_accessor.count
        
        # Get indices (faces)
        if primitive.indices is not None:
            indices_accessor = gltf.accessors[primitive.indices]
            result.triangle_count = indices_accessor.count // 3
        
        # Get bounds
        if position_accessor.min and position_accessor.max:
            result.bounds_min = position_accessor.min
            result.bounds_max = position_accessor.max
        
        result.valid = True
        return result
    
    except Exception as e:
        result.error_message = str(e)
        return result


def validate_manifest(manifest_path: Path) -> bool:
    """Validate buildings_manifest.json structure."""
    try:
        with open(manifest_path, 'r') as f:
            manifest = json.load(f)
        
        # Check required fields
        if "metadata" not in manifest or "buildings" not in manifest:
            logger.error("Manifest missing required fields")
            return False
        
        metadata = manifest["metadata"]
        buildings = manifest["buildings"]
        
        logger.info(f"Manifest validated: {len(buildings)} buildings recorded")
        return True
    
    except Exception as e:
        logger.error(f"Manifest validation failed: {e}")
        return False


# ============================================================================
# Main Validation Pipeline
# ============================================================================

def run_validation():
    """Validate all generated meshes."""
    meshes_dir = Path(CONFIG["meshes_dir"])
    
    if not meshes_dir.exists():
        logger.error(f"Meshes directory not found: {meshes_dir}")
        return
    
    # Find all GLB files
    glb_files = sorted(meshes_dir.glob("*.glb"))
    logger.info(f"Found {len(glb_files)} GLB files")
    
    # Validate each file
    results = []
    for idx, glb_path in enumerate(glb_files):
        if idx % 100 == 0:
            logger.info(f"Validating {idx + 1}/{len(glb_files)}...")
        
        result = validate_glb_file(glb_path)
        results.append(result)
    
    # Compute summary
    valid_count = sum(1 for r in results if r.valid)
    invalid_count = len(results) - valid_count
    total_size = sum(r.file_size_bytes for r in results)
    total_vertices = sum(r.vertex_count for r in results)
    total_triangles = sum(r.triangle_count for r in results)
    
    summary = ValidationSummary(
        timestamp=datetime.now().isoformat(),
        total_meshes=len(results),
        valid_meshes=valid_count,
        invalid_meshes=invalid_count,
        total_file_size_mb=total_size / (1024 * 1024),
        avg_vertices_per_mesh=total_vertices / max(valid_count, 1),
        avg_triangles_per_mesh=total_triangles / max(valid_count, 1),
        total_vertices=total_vertices,
        total_triangles=total_triangles
    )
    
    # Generate report
    report_path = Path(CONFIG["validation_report_path"])
    report_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(report_path, 'w') as f:
        f.write("# Building Mesh Validation Report\n\n")
        f.write(f"**Generated**: {summary.timestamp}\n\n")
        f.write("## Summary\n\n")
        f.write(f"- Total Meshes: {summary.total_meshes}\n")
        f.write(f"- Valid: {summary.valid_meshes}\n")
        f.write(f"- Invalid: {summary.invalid_meshes}\n")
        f.write(f"- Total File Size: {summary.total_file_size_mb:.1f} MB\n")
        f.write(f"- Total Vertices: {summary.total_vertices:,}\n")
        f.write(f"- Total Triangles: {summary.total_triangles:,}\n")
        f.write(f"- Avg Vertices/Mesh: {summary.avg_vertices_per_mesh:.0f}\n")
        f.write(f"- Avg Triangles/Mesh: {summary.avg_triangles_per_mesh:.0f}\n\n")
        
        if invalid_count > 0:
            f.write(f"## Invalid Meshes ({invalid_count})\n\n")
            for result in results:
                if not result.valid:
                    f.write(f"- {result.filename}: {result.error_message}\n")
    
    logger.info(f"Validation report saved to {report_path}")
    
    # Print summary
    logger.info("=" * 70)
    logger.info("MESH VALIDATION COMPLETE")
    logger.info("=" * 70)
    logger.info(f"Valid meshes: {summary.valid_meshes}/{summary.total_meshes}")
    logger.info(f"Total file size: {summary.total_file_size_mb:.1f} MB")
    logger.info(f"Total vertices: {summary.total_vertices:,}")
    logger.info(f"Total triangles: {summary.total_triangles:,}")
    logger.info("=" * 70)
    
    return summary


def create_unity_import_guide():
    """Create guide for importing meshes into Unity."""
    guide_path = Path(CONFIG["unity_import_guide_path"])
    guide_path.parent.mkdir(parents=True, exist_ok=True)
    
    guide = """# Unity Import Guide — Building Meshes

## Overview

This guide describes how to import generated building meshes into Unity for the Gothenburg Digital Twin project.

## Generated Assets

- **Mesh Files**: `Processed_data/building_meshes/*.glb`
- **Manifest**: `Processed_data/building_meshes/buildings_manifest.json`
- **Spatial Joins**: `Processed_data/spatial_joins/building_to_grid_cells.json`
- **Analytics**: `Processed_data/analytics/building_demographics.json`

## Import Process

### 1. Copy Asset Files

```bash
# Copy all GLB files to Unity project
cp Processed_data/building_meshes/*.glb Assets/Models/Buildings/

# Copy manifest for reference
cp Processed_data/building_meshes/buildings_manifest.json Assets/Data/
```

### 2. Configure Import Settings in Unity

For each GLB file:
1. Select in Project window
2. Inspector → Model tab:
   - Meshes: Enable all
   - Materials: Create new materials as needed
   - Optimize: Check "Optimize Mesh Data"
3. Apply

### 3. Create Building Manager Script

Example C# script pseudocode:

```csharp
public class BuildingManager : MonoBehaviour
{
    private Dictionary<string, GameObject> buildingMeshes;
    private Dictionary<string, BuildingData> buildingData;
    
    void Start()
    {
        LoadManifest("Data/buildings_manifest.json");
        LoadAnalytics("Data/building_demographics.json");
        LoadSpatialJoins("Data/building_to_grid_cells.json");
    }
    
    void OnBuildingClicked(string buildingId)
    {
        BuildingData data = buildingData[buildingId];
        
        // Display info panel
        InfoPanel.Show(
            buildingName: data.building_name,
            purpose: data.primary_purpose,
            height: data.height_m,
            population: data.total_population,
            demographics: data.age_distribution
        );
    }
}
```

### 4. Set Up Click Detection

Add colliders and raycast handler:

```csharp
void Update()
{
    if (Input.GetMouseButtonDown(0))
    {
        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        if (Physics.Raycast(ray, out RaycastHit hit))
        {
            string buildingId = hit.collider.gameObject.name;
            OnBuildingClicked(buildingId);
        }
    }
}
```

### 5. Display Info Panel

When building is selected, show:
- Building name
- Primary purpose (function)
- Height
- Grid cell population data
- Age distribution
- Education levels
- Employment sectors (if available)

## Data Structure Reference

### Manifest Format

```json
{
  "metadata": {
    "timestamp": "2026-04-23T...",
    "buildings_successfully_meshed": 220000,
    "total_vertices": 4500000,
    "total_triangles": 1200000
  },
  "buildings": [
    {
      "building_id": "bldg_000000",
      "object_id": "uuid-...",
      "height_m": 10.5,
      "glb_filename": "bldg_000000.glb",
      "centroid_x": 312345.5,
      "centroid_y": 6395000.5
    }
  ]
}
```

### Building Analytics Format

```json
[
  {
    "building_id": "bldg_000000",
    "overlapping_grid_cells": ["cell_id_1", "cell_id_2"],
    "total_population": 1250,
    "age_distribution": {
      "age_0_6": 80,
      "age_7_15": 120,
      "age_65_plus": 280
    },
    "education_distribution": {
      "gymnasium": 450,
      "post_gymnasium": 500
    }
  }
]
```

## Performance Considerations

- **220k+ meshes**: Consider LOD (Level of Detail) or culling
- **4.5M+ vertices**: Stream loading by grid cells
- **File size**: ~20GB total (use compression in production)

## Next Steps

1. ✅ Import meshes into Unity
2. Create Building and Grid managers
3. Implement click detection and info panel
4. Load and display spatial join data
5. Test interactive selection and analytics display
6. Optimize for target VR/desktop platform

## Troubleshooting

| Issue | Solution |
|-------|----------|
| Meshes not visible | Check colliders, layer masks, camera clipping planes |
| Info panel not appearing | Verify manifest and analytics JSON loaded correctly |
| Performance issues | Enable mesh batching, implement frustum culling, use LOD groups |
| Material issues | Apply white material to all meshes, adjust emission if needed |

---

See `CLAUDE.md` for full project standards and documentation.
"""
    
    with open(guide_path, 'w') as f:
        f.write(guide)
    
    logger.info(f"Unity import guide created: {guide_path}")


if __name__ == "__main__":
    run_validation()
    create_unity_import_guide()
